### PR TITLE
Add Vim support

### PR DESCRIPTION
**Pull request by sukima**
This is a pretty common and (arguably) necessary to provide the two most widely used Unix editors. Yes sublime is good but it isn't part of the server build and not everyone is happy with sublime.

### CODE REVIEW

**Comment by jpadilla** [comment]
I'm mostly :-1: on this since we're aiming for Juice Box being most useful for beginners, editors like vim are mostly used for "experienced" developers. I would still like to collect optional setups like these as part of this project with one line commands to install and run setups on existing/running Juice Box VMs. Perhaps have a folder with optional provisioning scripts that are copied into the VM and have instructions of commands to run from inside the already provisioned VM to install specific setups.

The same goes for #20.

@gcollazo thoughts?

**Comment by gcollazo** [comment]
I agree with VIM is better for advanced users. How is having optional setups like this + instructions different from telling students to run `sudo apt-get install <insert package here>`?

**Comment by sukima** [comment]
I disagree on the assumption that beginners are not "good enough" to explore well tested editors designed for programming Kinda like Sublime is used by advanced programmers. But that's my opinion since I start my first programming class using Vim and is a topic for another forum.

Anyway, I found that when  attempted a `sudo apt-get install` it fails till I first run a `sudo apt-get update` and so I think a better compromise to offer the following in the `README.html` that is installed:

> To edit text files you can use `nano` from the command line or the Sublime icon on the top of the screen. If you find you want a different editer (like Vim or Emacs) you can easily install them by first running `sudo apt-get update` and then `sudo apt-get install <editor package>`.

Thoughts? (Closing)

**Comment by jpadilla** [comment]
@sukima thanks for the feedback, will try something out regarding this in the next couple of days.

**Pull request closed without merging**
