### PR TITLE
Pyenv: Provides Python 2 and 3

### LINKED ISSUE #18: Python 3
Lots of inquiries to why Python 2 over Python 3. Might just install both next to each other and provide some aliases like `mkvirtualenv2.7` and `mkvirtualenv3.3`.

If anyone has a better setup for development with both versions, ideas are welcome.

### PR DESCRIPTION
**Pull request by nelsonjchen**
Usage is the same as a typical `pyenv` installation.

Addressing the concerns in #24, which means this Closes #24.

`pyenv`'s virtualenv plugin is also installed through `pyenv`'s installation script. See [yyuu/pyenv-virtualenv](https://github.com/yyuu/pyenv-virtualenv) for usage details. It's more than adequate to provide a Python virtual environment and as a `*env` family of tools user, I find it natural and nicely integrated. It's not `virtualenvwrapper` but it'll do just fine. Someone else can go make a PR for pyenv's `virtualenvwrapper` plugin if they really want to.

Closes #18. Provides Python 2 and Python 3.

### CODE REVIEW

**Comment by jpadilla** [comment]
@nelsonjchen thanks for putting this together. Gonna try it out now.

**Comment by jpadilla** [comment]
I'm now debating if we want to install Python 3 here by default. It's very easy now to install any other version you want  thanks to pyenv. Our ruby/rvm setup only has one version installed by default. Our io.js/nvm setup has only one version installed by default.

@gcollazo thoughts?

**Comment by gcollazo** [comment]
In my experience participating as a student/TA in Python tutorials, the actual version used is not that important.

What we need for this project is a working setup out-of-the-box, no additional steps required. Just type `python` in the terminal and it just works. Let us be reminded that the target is beginners and that the goal of the project is not "maximum flexibility" but "minimal effort required".

I would vote to have a single version of Python in the 3.x range.

**Comment by jpadilla** [comment]
@gcollazo that sounds about right. Will install and make default `3.4.3` only.

**Pull request merged**
